# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c84d23c1b0f457e4e8e4e3f3237a9b6ad4e30a5c75d0d4e7f186a5ac26d7ab42690de1a7607e09e9936c7bf99f29a7b5a2471dcf05e4032b54c80e69892eecd9

test:
  secret_key_base: d6d4aa235df540e6a1fc62a2f4de35aed5035f8d6f4b9ad7f1ba1b75683564f1d52fa28eb295685b2885ff78343e287ac76d09363b49c3b930af9e6bf1c8ab21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
